// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABddhn2jWbK6jsFGQoYdvpV3R3h0uMwpo',
    appId: '1:12566835162:web:973189901cdce5abd31ae3',
    messagingSenderId: '12566835162',
    projectId: 'olx-app-33717',
    authDomain: 'olx-app-33717.firebaseapp.com',
    storageBucket: 'olx-app-33717.appspot.com',
    measurementId: 'G-P61EQBHCF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Vyf9RKe03jduZzU7XMZrgb8LfgYatqY',
    appId: '1:12566835162:android:113916775902a6ebd31ae3',
    messagingSenderId: '12566835162',
    projectId: 'olx-app-33717',
    storageBucket: 'olx-app-33717.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSUpYGNveSYQcaOSEqly2MAmRDFK2oa8U',
    appId: '1:12566835162:ios:bd7cdaa0c7e254ffd31ae3',
    messagingSenderId: '12566835162',
    projectId: 'olx-app-33717',
    storageBucket: 'olx-app-33717.appspot.com',
    iosBundleId: 'com.samionyx.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSUpYGNveSYQcaOSEqly2MAmRDFK2oa8U',
    appId: '1:12566835162:ios:bd7cdaa0c7e254ffd31ae3',
    messagingSenderId: '12566835162',
    projectId: 'olx-app-33717',
    storageBucket: 'olx-app-33717.appspot.com',
    iosBundleId: 'com.samionyx.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPct5u5rP3MXmmL68tBLgnkf8HkKh3XGU',
    appId: '1:12566835162:web:a64c26ea9e126990d31ae3',
    messagingSenderId: '12566835162',
    projectId: 'olx-app-33717',
    authDomain: 'olx-app-33717.firebaseapp.com',
    storageBucket: 'olx-app-33717.appspot.com',
    measurementId: 'G-EGQN2M9SEF',
  );
}
